name: GenAi Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'qa'
        type: choice
        options:
          - 'qa'
          - 'dev'
          - 'prod'
      testGroup:
        description: 'Test group to execute'
        required: true
        default: '@full-regression'
        type: choice
        options:
          - '@full-regression'
          - '@login'
      shardCount:
        description: 'Number of shards/workers'
        required: true
        default: '2'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        shard: [1, 2] # Esto crea dos jobs paralelos.
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Playwright Tests
      run: npm run test:genai-all -- --grep=${{ github.event.inputs.testGroup }} --shard=${{ matrix.shard }}/${{ github.event.inputs.shardCount }}
      env:
        APP_ENV: ${{ github.event.inputs.environment }}
    
    - name: Upload Allure results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-results-${{ matrix.shard }}
        path: allure-results/

  consolidate-reports:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Download Allure results artifacts
      uses: actions/download-artifact@v2
      with:
        path: consolidated-results

    - name: Install Allure Commandline
      run: npm install -g allure-commandline

    - name: Generate Allure report
      run: allure generate consolidated-results/ -o allure-report/

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: Allure Report
        path: allure-report/

