name: GenAi Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'qa'
        type: choice
        options:
          - 'qa'
          - 'dev'
          - 'prod'
      shardCount:
        description: 'Number of shards/workers'
        required: true
        default: '2'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        include:
          - env: ${{ github.event.inputs.environment }}
            shard: 1
            totalShards: ${{ github.event.inputs.shardCount }}
          - env: ${{ github.event.inputs.environment }}
            shard: 2
            totalShards: ${{ github.event.inputs.shardCount }}
            
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Playwright Tests
      run: npm run test:genai-all -- --shard=${{ matrix.env }} --shard=${{ matrix.shard }}/${{ matrix.totalShards }}
      env:
        APP_ENV: ${{ matrix.env }}

    - name: Generate Allure report
      if: always()
      run: npm run allure:html-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Allure Report ${{ matrix.env }}
        path: public/
